services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles:
      - dev

  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_app_dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - postgres
    profiles:
      - dev

  app_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_app_prod
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    profiles:
      - prod

volumes:
  pgdata:
