services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
